services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=upload

    volumes:
      - './docker:/docker-entrypoint-initdb.d'